### ISSUE TITLE
Impossible de se connecter

### ISSUE THREAD

**Issue by PLMbugz** [BuggleInc/webPLM#155]
Lorsque j'essaie de me connecter avec un compte tiers (G+, GitHub, pas testé avec facebook), une fenêtre s'ouvre et se ferme directement. J'ai un message 'echec de la connexion, échec de la requête'. D'autre part, si j'essaie de me connecter avec un compte PLM, la fenêtre s'ouvre en affichant 502 : Bad Gateway.
- Comment j'ai produit le bug : en essayant de me connecter une première fois avec un compte G+ (ou GitHub ça fait pareil)
- Ce qui devrait se passer : la connexion devrait aboutir
- Ce qui se passe : la connexion n'aboutit pas.

Merci !

--

Programming Language: Java
Lang: fr
PLM version: 2.6-pre (20150202)
webPLM version: 2.1.1

**Comment by mquinson** [comment]
@MatthieuNICOLAS could you please have a look on the authentication server, please? 

Anonymous submitter, are you sure that you don't have an AdBlock activated?

Thanks, Mt.

**Comment by MatthieuNICOLAS** [comment]
It was due to a reboot of the machine hosting our containers. Since MongoDB is installed on this server, it started a MongoDB instance before restarting our own containers. Then, since the port was already used by this instance, our MongoDB container could not start, preventing others containers depending on this one (PLM-accounts and PLM-profiles) to work properly.

I disabled the MongoDB service to prevent this problem from occuring again, thus closing this issue.

**Comment by mquinson** [comment]
@MatthieuNICOLAS so, where are the login information, now? 

Anyway, thanks for taking care of this.
